### PR TITLE
Adds venue and year comparisons.

### PR DESCRIPTION
**Pull request by jakemannix**
also extra counts for empty titles, authors, and venues, as a low-pass filter.

### CODE REVIEW

**Comment by jakemannix** [comment]
actually hold off on this.  There are a bunch more changes needed to get this to work in the backend pipeline.

**Comment by jakemannix** [comment]
Ok, it looks like this might actually be just fine now.  I'm using this code (published locally) on my s2-offline branch, and it's working now, finally.

Let me know when you can get this reviewed.

**Comment by vha14** [comment]
LGTM. Bump version to 1.0.3?

**Comment by vha14** [comment]
Couldn't assign this back to you Jake. Feel free to merge/publish when ready.

**Pull request merged**
